### ISSUE TITLE
Need to add absent source files to repository in order to provide project Build

### ISSUE THREAD

**Issue by VladislavShubnikov** [AbayK/LungCancer#7]
Seems, some files are forgottent and should be added onto repository:
segment.h

Now project application **cant be build** from sources.

Compilation log:

src\segment.cpp(19): error C2653: 'SegmentStr': is not a class or namespace name
1>src\segment.cpp(19): error C2065: 'VolTexture': undeclared identifier

**Comment by AbayK** [comment]
segment.h already exist in repository. I commited vs filter fix (maybe it will be help with this problem)

**Comment by VladislavShubnikov** [comment]
Everything fine
